pipeline
{
    agent any

    environment {
        registry = "codestorm2020/codestorm2020"
        registryCredential = 'docker_credentials'
    }

    stages
    {
        stage('Build')
        {
            steps
            {
                sh '''
                    cd APIGateway/RESTGateway
                    script
                    {
                        docker.build registry + ":$BUILD_NUMBER"
                    }
                '''
            }
        }
     }
}

