node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
    	withCredentials([usernamePassword( credentialsId: 'cd456d2d-aed2-4582-b272-28fc33cd5507', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    sh "docker-compose -f ./APIGateway/RESTGateway/docker-compose.yml build"
	}
    }
	
    stage('Push image') {
	withCredentials([usernamePassword( credentialsId: 'docker_credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    def registry_url = "registry.hub.docker.com/"
            sh "docker login -u $USER -p $PASSWORD docker.io"
	    docker.withRegistry("https://hub.docker.com/", "docker_credentials") {
	          sh "docker push codestorm/api-5ateway"
          	
	    }
	}
    }
}
