pipeline
{
    agent any
    tools {
            nodejs 'NodeJs 13.11.0'
        }

    environment {
        registry = "docker_hub_account/codestorm2020"
        registryCredential = 'docker_credentials'
    }

    stages
    {
        stage('Build')
        {
            steps
            {
                sh '''
                    sh "sudo -S docker network create --driver bridge codestorm-default-network || true"
                   	sh "sudo -S docker-compose -f ./APIGateway/RESTGateway//docker-compose.yml build"

                '''
            }
        }
     }
}

