pipeline
{
    agent any
    tools {
            maven 'Maven 3.6.3'
        }

    stages
    {
        stage('Build')
                {
                    steps
                    {
                        sh '''
                            cd UserManagement
                            mvn -B -DskipTests clean package
                        '''
                        withCredentials([usernamePassword( credentialsId: 'Jenkins_credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')])
                        {
                            sh "sudo -S docker-compose -f ./UserManagement/docker-compose.yml build"
                        }
                    }
                }

        stage('Install')
        {
            steps
            {
                sh '''
                    cd UserManagement
                    mvn clean install
                '''
            }
        }

        stage('Push Stage')
        {
            steps
            {
                script
                {
                    withCredentials([usernamePassword( credentialsId: 'Jenkins_credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')])
                    {
                        def registry_url = "registry.hub.docker.com/"
                        sh "sudo -S docker login -u $USER -p $PASSWORD docker.io"
                        docker.withRegistry("http://${registry_url}", "docker_credentials")
                        {
                            sh "sudo -S docker push codestorm2020/api-gateway"
                        }
                    }
                }
            }
        }
    }
}
