pipeline
{
    agent
    {
        docker
        {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }

    stages
    {
        stage('Build')
                {
                    steps
                    {
                        sh '''
                            cd UserManagement
                            mvn -B -DskipTests clean package
                        '''
                    }
                }

        stage('Install')
        {
            steps
            {
                sh '''
                    cd UserManagement
                    mvn clean install
                '''
            }
        }

    }
}