node {
    stage('Code checkout') {
        checkout scm
    }

    stage('Build image') {
    	withCredentials([usernamePassword( credentialsId: 'Jenkins_credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    sh "sudo -S docker-compose -f ./ModelExecution/docker-compose.yml build"
	}
    }
	
    stage('Push image') {
	withCredentials([usernamePassword( credentialsId: 'docker_credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
	    def registry_url = "registry.hub.docker.com/"
            sh "sudo -S docker login -u $USER -p $PASSWORD docker.io"
	    docker.withRegistry("http://${registry_url}", "docker_credentials") {
	        sh "sudo -S docker push codestorm2020/modelexecution"
          	
	    }
	}
    }
}
